export default {
  cgTable: {
    title: {
      list: 'Code design',
      record: 'Code design',
      groupCgTableModule: 'Table define',
      groupCgTableImports: 'Code design',
      code: 'Cg table'
    },
    action: {
      create: 'Create',
      syncConfirm: 'Confirm sync',
      sync: 'Sync',
      generatorConfirm: 'Confirm generator',
      generator: 'Generator',
      scanCodeConfirm: 'Confirm scan code',
      scanCode: 'Scan code',
      flowSyncConfirm: 'Confirm flow sync',
      flowSync: 'Flow sync',
      fields: 'Fields'
    },
    field: {
      id: 'Id',
      codeValid: 'Please input correct value for code',
      code: 'Code',
      nameValid: 'Please input correct value for name',
      name: 'Name',
      titleValid: '分隔中文和英文',
      title: 'Title',
      subPackageValid: 'Please input correct value for sub package',
      subPackage: 'Sub package',
      entityValid: 'Please input correct value for entity',
      entity: 'Entity',
      templateValid: 'Please input correct value for template',
      template_0: '',
      template: 'Template',
      trialLicence: 'Trial licence',
      trialDays: 'Trial days',
      actionListValid: 'Please input correct value for action list',
      actionList_0: '',
      actionList_1: '',
      actionList_2: '',
      actionList_3: '',
      actionList_4: '',
      actionList_5: '',
      actionList_6: '',
      actionList_7: '',
      actionList_8: '',
      actionList_9: '',
      actionList_10: '',
      actionList: 'Action list',
      imports: 'Imports',
      controllerExtends: 'Controller extends',
      pojoImports: 'Pojo imports',
      pojoExtends: 'Pojo extends',
      pojoJavaCode: 'Pojo java code',
      creator: 'Creator',
      flowDynaFieldsOp: 'Flow dyna fields op',
      flowDynaFieldsCp: 'Flow dyna fields cp',
      projectId: 'Project id'
    }
  }
}
