export default {
  devPeople: {
    title: {
      list: 'Register people',
      select: 'Select people',
      record: 'People',
      groupDevPeopleRealName: 'Bae informations',
      groupDevPeopleCardNo: 'Authentication',
      sample: 'Vein sample',
      code: 'People'
    },
    action: {
      getRegistered: 'Get registered',
      syncRegFingersConfirm: 'Confirm sync reg fingers',
      syncRegFingers: 'Sync reg fingers',
      sample: 'Sample',
      connectDevice: 'Connect device',
      registerFinger: 'Register finger',
      verifyFinger: 'Verify finger',
      matchFinger: 'Match finger',
      removeFingerConfirm: 'Confirm remove finger',
      removeFinger: 'Remove finger',
      resetDevice: 'Reset device'
    },
    field: {
      userNoValid: 'Please input correct value for user no',
      userNo: 'User no',
      realName: 'Real name',
      sex: 'Sex',
      birthDate: 'Birth date',
      orgCode: 'Org code',
      dutyRank: 'Duty rank',
      cardNoValid: 'Please input correct value for card no',
      cardNo: 'Card no',
      idType: 'Id type',
      idNumber: 'Id number',
      userType_0: 'Administrator',
      userType_1: 'User',
      userType: 'User type',
      mobilePhone: 'Mobile phone',
      email: 'Email',
      registerType: 'Register type',
      validDate: 'Valid date',
      expiredDate: 'Expired date',
      regTime: 'Reg time',
      devPassword: 'Dev password',
      regFingers: 'Reg fingers',
      note: 'Note',
      idNation: 'Id nation',
      photo: 'Photo',
      homeAddr: 'Home addr',
      fingerNo1: 'Finger no1',
      fingerNo2: 'Finger no2',
      fingerType_0: 'Right index finger',
      fingerType_1: 'Right middle finger',
      fingerType_2: 'Right ring finger',
      fingerType_3: 'Left index finger',
      fingerType_4: 'Left middle finger',
      fingerType_5: 'Left ring finger',
      fingerType_6: 'Customize 1',
      fingerType_7: 'Customize 2',
      fingerType: 'Finger type',
      warning: 'Warning'
    }
  }
}
