export default {
  reader: {
    checkU53: 'Please check U53 service',
    u53error: 'U53 request failure',
    resetOK: 'Reset success, waiting twice ticking beep',
    deleteOneFinger: 'Please remove one finger first',
    noneAuth: 'None register for the finger',
    readFromDevice: 'Please read vein on the device',
    authInfo: {
      bytes:'Template bytes',
      matches:'Matches',
      capacity:'Template capacity',
      authTimes:'Auth times',
      totalTimes:'Total times',
      status:'Status',
      details:'Details',
      score: 'Score'
    },
    dataDict: {
      dev_access_state_0: 'Pass',
      dev_access_state_1: 'Refuse',
      dev_access_state_2: 'Force',
      dev_auth_type_1: 'Vein',
      dev_auth_type_2: 'Card + Vein',
      dev_auth_type_3: 'Card or Vein',
      dev_auth_type_4: 'Server auth',
      dev_auth_type_5: 'Password + Vein',
      dev_auth_type_6: 'Password or Vein',
      dev_auth_type_7: 'Password, Vein or Card',
      dev_auth_type_8: 'Vein or (Card + Password)',
      dev_mode_MJ: 'Entrance',
      dev_mode_XG: 'Patrol',
      dev_mode_AD: 'Sign in',
      dev_mode_ON: 'Work on',
      dev_mode_OFF: 'Work off',
      dev_permit_mode_0: 'Unauthorized',
      dev_permit_mode_1: 'Need audit',
      dev_permit_mode_2: 'Audit authority',
      dev_permit_mode_4: 'Authorized',
      dev_permit_mode_14: 'Authorized on work time',
      dev_wg_form_3: 'customized',
      dev_wg_out_1: 'Fixed',
      dev_wg_out_2: 'Number',
      dev_wg_out_3: 'Card no',
      dev_wg_out_4: 'Area + No',
      cg_modules_framework: 'Framework',
      cg_modules_codegenerator: 'Code generator',
      cg_modules_attendance: 'Attendance',
      cg_modules_reader: 'Device manage',
      cg_modules_svas: 'Auth by svas server',
      cg_modules_SvasClient: 'Svas client'
    }
  }
}
