
spring:
   datasource:
      max-active : 20
      max-idle : 8
      min-idle : 8
      initial-size : 10
   http: 
      encoding:
         charset: UTF-8
         enabled: true
         force: true      
   mvc:
      static-path-pattern: /res/**
      favicon:
         enabled: false
   resources:
      static-locations: classpath:/static/
   jackson:
      time-zone: GMT+8
server: 
   tomcat:
      uri-encoding: UTF-8   
management:
   endpoints:
       web: 
          exposure:         
            include: '*'
   endpoint: 
      health: 
         show-details: always
      shutdown: 
         enabled: false    
logging: 
   file: log/iotequ.log
   level: 
      root: error
      org.springframework: error
      org.mybatis: error
      top.iotequ: error

mybatis:
   mapper-locations : classpath*:/mybatis/**/*.xml
   configuration: 
      cache-enabled : true
      map-underscore-to-camel-case: true


svas:
   matchTestSyncMinutes: 0  # 打开验证测试并设置同步等待时间
   matchTrace: false        # 验证跟踪
   thresh: 380              # 默认阈值
   userNoPrefix : "023"     # userNo 前缀
   userNoMminLength: 10     # userNo 最小长度

   sn : 2090-B663-7907-628A-2796-148D-6039-7195
   sn_dev_reader : D51C-6B94-A9DE-0841-2B64-27E0-5227-B376
   sn_ad_employee : DCB5-13ED-D426-85D3-169B-BBBC-0BD5-74DA
   sn_pm_people_group : 6544-FDCF-0B1B-80B5-EE0D-2A01-0C18-1AEC
   sn_pm_people : 6544-FDCF-0B1B-80B5-EE22-202C-1308-05EC

   datasource:
      host: localhost
      port: 3306
      user: root
      password: root
      schema: iotequ3

   adjust:
      autoUpdateTemplate: false   # 自动用验证数据更新字典
      templatesMustMatch: false   # 插入模板三个词典必须匹配
      multiMatchedWeight: 0       # 相同模板的多个词典多次匹配增加权重
      maxMatchedWeight: 0         # 最大匹配满足条件增加权重
      maxMatchedCondition: 100    # 最大匹配条件（差值必须大于该值)
