server:
   port: 8188
   tomcat:
      uri-encoding: UTF-8
   servlet:
      context-path: /
      session:
         timeout: PT10M  #会话最大保持时间，以秒为单位，不低于1分钟，
      encoding:
         charset: UTF-8
         enabled: true
         force: true
spring:
   mvc:
      static-path-pattern: /res/**
   resources:
      static-locations: classpath:/static/
   jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
management:
   endpoints:
       web:
          exposure:
            include: '*'
   endpoint:
      health:
         show-details: always
      shutdown:
         enabled: false
#日志输出
logging:
   file:
      name: log/svas.log
   level:
      root: error
      org.springframework: error
      top.iotequ: error
