-- ----------------------------
-- Table structure for ad_special_shift_time
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','AD_SPECIAL_SHIFT_TIME','IOTEQU');
CREATE TABLE "IOTEQU"."AD_SPECIAL_SHIFT_TIME" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "SPECIAL_SHIFT_ID" INTEGER NOT NULL,
  "NAME" VARCHAR2(45 BYTE) NOT NULL,
  "START_TIME" DATE NOT NULL,
  "END_TIME" DATE NOT NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_AD_SPECIAL_SHIFT_TIME','IOTEQU');
CREATE SEQUENCE SEQUENCE_AD_SPECIAL_SHIFT_TIME;

-- ----------------------------
-- Table structure for ad_shift_time
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','AD_SHIFT_TIME','IOTEQU');
CREATE TABLE "IOTEQU"."AD_SHIFT_TIME" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "SHIFT_ID" INTEGER NOT NULL,
  "NAME" VARCHAR2(100 BYTE) NOT NULL,
  "WEEK_DAYS" VARCHAR2(45 BYTE) DEFAULT '1,2,3,4,5' NOT NULL,
  "START_WORK_TIME" DATE NOT NULL,
  "END_WORK_TIME" DATE NOT NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_AD_SHIFT_TIME','IOTEQU');
CREATE SEQUENCE SEQUENCE_AD_SHIFT_TIME;

-- ----------------------------
-- Table structure for ad_org
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','AD_ORG','IOTEQU');
CREATE TABLE "IOTEQU"."AD_ORG" (
  "ORG_CODE" INTEGER NOT NULL PRIMARY KEY,
  "SHIFT_ID" INTEGER NULL,
  "HR" VARCHAR2(36 BYTE) NULL,
  "MANAGER" VARCHAR2(36 BYTE) NULL,
  "MANAGE_LIMIT" INTEGER NULL,
  "DEVIATION" INTEGER NULL,
  "FLOAT_LIMIT" INTEGER NULL,
  "ABSENT_LIMIT" INTEGER NULL,
  "FREE_WORK_LIMIT" INTEGER NULL
);

-- ----------------------------
-- Table structure for ad_exception
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','AD_EXCEPTION','IOTEQU');
CREATE TABLE "IOTEQU"."AD_EXCEPTION" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "SHIFT_ID" INTEGER NOT NULL,
  "END_DATE" DATE NOT NULL,
  "START_DATE" DATE NOT NULL,
  "WEEK_DAY" INTEGER NOT NULL,
  "DESCRIPTION" VARCHAR2(100 BYTE) NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_AD_EXCEPTION','IOTEQU');
CREATE SEQUENCE SEQUENCE_AD_EXCEPTION;

-- ----------------------------
-- Table structure for ad_employee
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','AD_EMPLOYEE','IOTEQU');
CREATE TABLE "IOTEQU"."AD_EMPLOYEE" (
  "ID" VARCHAR2(36 BYTE) NOT NULL PRIMARY KEY,
  "EMPLOYEE_NO" VARCHAR2(32 BYTE) NOT NULL UNIQUE,
  "EM_LEVEL" INTEGER NULL,
  "IS_ATTENDANCE" NUMBER(1) DEFAULT 1 NOT NULL,
  "ENTER_DATE" DATE NULL,
  "LEAVE_DATE" DATE NULL,
  "OVERTIME_MINUTES" INTEGER DEFAULT 0 NOT NULL,
  "SHIFT_ID" INTEGER NULL
);

-- ----------------------------
-- Table structure for ad_approve_list
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','AD_APPROVE_LIST','IOTEQU');
CREATE TABLE "IOTEQU"."AD_APPROVE_LIST" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "APPROVER" VARCHAR2(36 BYTE) NULL,
  "APPROVE_TIME" DATE NOT NULL,
  "STATE1" INTEGER NULL,
  "STATE0" INTEGER NULL,
  "APPROVE_NOTE" VARCHAR2(200 BYTE) NULL,
  "ADJUST_ID" VARCHAR2(32 BYTE) NOT NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_AD_APPROVE_LIST','IOTEQU');
CREATE SEQUENCE SEQUENCE_AD_APPROVE_LIST;

-- ----------------------------
-- Table structure for ad_special_shift
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','AD_SPECIAL_SHIFT','IOTEQU');
CREATE TABLE "IOTEQU"."AD_SPECIAL_SHIFT" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "SHIFT_MODE" INTEGER NOT NULL,
  "NAME" VARCHAR2(45 BYTE) NOT NULL,
  "MODE_PROPERTY" INTEGER NULL,
  "START_DATE" DATE NOT NULL,
  "END_DATE" DATE NOT NULL,
  "ORG_CODES" VARCHAR2(300 BYTE) NOT NULL,
  "SEX_PROPERTY" INTEGER NULL,
  "AGE_PROPERTY0" INTEGER NULL,
  "AGE_PROPERTY1" INTEGER NULL,
  "LEVEL_PROPERTY0" INTEGER NULL,
  "LEVEL_PROPERTY1" INTEGER NULL,
  "DESCRIPTION" VARCHAR2(45 BYTE) NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_AD_SPECIAL_SHIFT','IOTEQU');
CREATE SEQUENCE SEQUENCE_AD_SPECIAL_SHIFT;

-- ----------------------------
-- Table structure for ad_shift
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','AD_SHIFT','IOTEQU');
CREATE TABLE "IOTEQU"."AD_SHIFT" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "NAME" VARCHAR2(45 BYTE) NOT NULL,
  "AD_MODE" INTEGER DEFAULT 1 NOT NULL,
  "START_DATE" DATE NOT NULL,
  "END_DATE" DATE NOT NULL,
  "MINUTES_PER_DAY" INTEGER DEFAULT 480 NOT NULL,
  "DESCRIPTION" VARCHAR2(200 BYTE) NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_AD_SHIFT','IOTEQU');
CREATE SEQUENCE SEQUENCE_AD_SHIFT;

-- ----------------------------
-- Table structure for ad_day_result
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','AD_DAY_RESULT','IOTEQU');
CREATE TABLE "IOTEQU"."AD_DAY_RESULT" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "ORG_CODE" INTEGER NOT NULL,
  "ORG_NAME" VARCHAR2(100 BYTE) NOT NULL,
  "EMPLOYEE" VARCHAR2(45 BYTE) NOT NULL,
  "EMPLOYEE_NO" VARCHAR2(45 BYTE) NOT NULL,
  "REAL_NAME" VARCHAR2(45 BYTE) NOT NULL,
  "AD_DATE" DATE NOT NULL,
  "SHIFT_NAME" VARCHAR2(45 BYTE) NOT NULL,
  "STATE" INTEGER NOT NULL,
  "STATE_NAME" VARCHAR2(45 BYTE) NOT NULL,
  "TIMES" INTEGER DEFAULT 1 NOT NULL,
  "MINUTES" INTEGER DEFAULT 0 NOT NULL,
  "WORK_MINUTES" INTEGER DEFAULT 0 NOT NULL,
  "SHIFT_ID" INTEGER DEFAULT 0 NOT NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_AD_DAY_RESULT','IOTEQU');
CREATE SEQUENCE SEQUENCE_AD_DAY_RESULT;

-- ----------------------------
-- Table structure for ad_data
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','AD_DATA','IOTEQU');
CREATE TABLE "IOTEQU"."AD_DATA" (
  "ID" CHAR(32) NOT NULL PRIMARY KEY,
  "EMPLOYEE_NO" VARCHAR2(45 BYTE) NOT NULL,
  "REC_SOURCE_TYPE" VARCHAR2(45 BYTE) DEFAULT 'D10' NOT NULL,
  "REC_SOURCE" VARCHAR2(45 BYTE) NULL,
  "REC_TYPE" INTEGER DEFAULT 3 NOT NULL,
  "REC_TIME" DATE NOT NULL,
  "IS_USED" NUMBER(1) DEFAULT '0' NOT NULL
);
CALL REMOVE_OBJECT('INDEX','INDEX_AD_DATA_EMPLOYEE_NO','IOTEQU');
CREATE INDEX "IOTEQU"."INDEX_AD_DATA_EMPLOYEE_NO" ON "IOTEQU"."AD_DATA"("EMPLOYEE_NO");

-- ----------------------------
-- Table structure for ad_adjust
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','AD_ADJUST','IOTEQU');
CREATE TABLE "IOTEQU"."AD_ADJUST" (
  "ID" CHAR(32) NOT NULL PRIMARY KEY,
  "EMPLOYEE" VARCHAR2(36 BYTE) NOT NULL,
  "ORG_CODE" INTEGER NOT NULL,
  "HR" VARCHAR2(45 BYTE) NULL,
  "ADJUST_TYPE" INTEGER DEFAULT 10 NULL,
  "STATE" INTEGER NOT NULL,
  "REGISTER_TIME" DATE NOT NULL,
  "START_TIME" DATE NULL,
  "END_TIME" DATE NULL,
  "DESCRIPTION" VARCHAR2(500 BYTE) NOT NULL,
  "APPROVER" VARCHAR2(36 BYTE) NULL,
  "APPROVE_ORG" INTEGER NULL,
  "ADD_FILE" VARCHAR2(200 BYTE) NULL
);

ALTER TABLE "IOTEQU"."AD_SPECIAL_SHIFT_TIME" ADD CONSTRAINT "IOTEQU"."FK_AD_SPECIAL_SHIFT_TIME_SPECIAL_SHIFT_ID_AD_SPECIAL_SHIFT_ID" FOREIGN KEY("SPECIAL_SHIFT_ID") REFERENCES "IOTEQU"."AD_SPECIAL_SHIFT"("ID") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "IOTEQU"."AD_SHIFT_TIME" ADD CONSTRAINT "IOTEQU"."FK_AD_SHIFT_TIME_SHIFT_ID_AD_SHIFT_ID" FOREIGN KEY("SHIFT_ID") REFERENCES "IOTEQU"."AD_SHIFT"("ID") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "IOTEQU"."AD_ORG" ADD CONSTRAINT "IOTEQU"."FK_AD_ORG_ORG_CODE_SYS_ORG_ORG_CODE" FOREIGN KEY("ORG_CODE") REFERENCES "IOTEQU"."SYS_ORG"("ORG_CODE") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "IOTEQU"."AD_EXCEPTION" ADD CONSTRAINT "IOTEQU"."FK_AD_EXCEPTION_SHIFT_ID_AD_SHIFT_ID" FOREIGN KEY("SHIFT_ID") REFERENCES "IOTEQU"."AD_SHIFT"("ID") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "IOTEQU"."AD_EMPLOYEE" ADD CONSTRAINT "IOTEQU"."FK_AD_EMPLOYEE_ID_SYS_USER_ID" FOREIGN KEY("ID") REFERENCES "IOTEQU"."SYS_USER"("ID") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "IOTEQU"."AD_APPROVE_LIST" ADD CONSTRAINT "IOTEQU"."FK_AD_APPROVE_LIST_ADJUST_ID_AD_ADJUST_ID" FOREIGN KEY("ADJUST_ID") REFERENCES "IOTEQU"."AD_ADJUST"("ID") ON DELETE CASCADE ON UPDATE CASCADE;
