#端口以及主目录路径   
server:
   port : 8188
   servlet: 
      context-path : /
      session:
         timeout: PT1H  #会话最大保持时间，以秒为单位，不低于1分钟，
#配置ssl请将 server.port 配置 为 443，然后配置以下参数
#   http:
#      port : 80       
#   ssl:
#      key-store: webapp/ssl_www.svein.com.cn.pfx
#      key-store-password: xipYs081
#      keyStoreType: PKCS12
spring:
# 正式环境设为false
   devtools:
      add-properties: true

# 群集环境需要配置redis服务
#   redis:
#      url: redis://localhost:6379
#      url: redis://192.168.1.162:30379
   #数据库连接配置
   datasource:
      url : jdbc:mysql://localhost:3306/iotequ3?characterEncoding=utf8&useSSL=true&allowMultiQueries=true&serverTimezone=Asia/Chongqing
      username : root
      password : root
      driverClassName : com.mysql.cj.jdbc.Driver
      
#      url : jdbc:sqlserver://localhost:1433;databaseName=iotequ
#      driverClassName : com.microsoft.sqlserver.jdbc.SQLServerDriver
#      username : sa
#      password : root

#      url : jdbc:oracle:thin:@127.0.0.1:1521:iotequ
#      driverClassName : oracle.jdbc.driver.OracleDriver
#      username : sa
#      password : root      

#文件上传保存地址，大小限制
   upload-path: web/uploadfiles
   servlet:
      multipart:
         maxFileSize: 100MB
         maxRequestSize: 100MB   
   jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
#日志输出
logging:
   file: 
      name: log/iotequ.log
   level: 
      root: info
      org.springframework: info
      org.mybatis: info
      top.iotequ: info

#mybatis输出sql语句
#mybatis:
#   configuration:
#      logImpl: org.apache.ibatis.logging.stdout.StdOutImpl

#代码生成配置  
generator: 
    path: D:/iotequ/web/generator/3.0.1
    org: top.iotequ
    project : codegenerator
    codepath : E:/J2EE/iotequ/3.0.1/
    nosamplecode : true
    localMode : true

#授权，svas配置
35F8-32D8-296E-37C7-7C52-F069-6739-3930:
   sn : 2090-B663-7907-628A-2796-148D-6039-7195
   sn_reader : 315C-E25F-590E-2A07-DC72-CA8C-9A50-D227
   sn_ad_employee : DCB5-13ED-D426-85D3-169B-BBBC-0BD5-74DA
   sn_pm_people_group : 6544-FDCF-0B1B-80B5-EE0D-2A01-0C18-1AEC
   sn_pm_people : 6544-FDCF-0B1B-80B5-EE22-202C-1308-05EC
   sn_pm_project : 6544-FDCF-1C1B-9ABC-E826-3D1E-3C1D-18F3

F265-49BD-87BC-FC8B-04F7-5A81-CDD9-9507:
   sn: FFC2-EADF-E88E-80C3-7798-6ACE-0B6F-9F20
   sn_reader: ED79-E6B8-A0BD-10C0-5721-133E-B571-5939
   sn_ad_employee: 7DE2-7047-AA16-F937-948F-489B-2966-7CD5
   sn_pm_people_group: D71D-BDA3-15A2-D060-4F21-F316-1E87-6E83
   sn_pm_people: D71D-BDA3-15A2-D060-4F0E-F93B-0197-7183
   sn_pm_project: D71D-BDA3-02A2-CA69-490A-E409-2E82-6C9C
1D4B-A54D-CBA2-9034-6D88-012B-AC5C-4CF6:
   sn : C9DF-DFD0-94D4-3642-C3C4-A37F-E078-72D0
   sn_reader : 0D7F-316C-C1D9-7803-F689-38B1-39FD-C950
   sn_ad_employee : 61BE-8C98-451F-75EE-5418-C1D1-0DF1-C61D

svas:
   matchTestSyncMinutes: 0  # 打开验证测试并设置同步等待时间
   matchTrace: false        # 验证跟踪
   thresh: 380              # 默认阈值
   userNoPrefix : "023"     # userNo 前缀
   userNoMminLength: 10     # userNo 最小长度

   datasource:
      host: localhost
      port: 3306
      user: root
      password: root
      schema: iotequ3

   adjust:
      autoUpdateTemplate: false   # 自动用验证数据更新字典
      templatesMustMatch: false   # 插入模板三个词典必须匹配
      multiMatchedWeight: 0       # 相同模板的多个词典多次匹配增加权重
      maxMatchedWeight: 0         # 最大匹配满足条件增加权重
      maxMatchedCondition: 100    # 最大匹配条件（差值必须大于该值)
#   url: https://www.svein.com.cn
#   client_id: svas
#   client_secret: e10adc3949ba59abbe56e057f20f883e 
#   scope: api
  
#微信授权登录 
wechat:
   loginUrl : https://www.svein.com.cn/res/wechat
   checkUrl : https://www.svein.com.cn/res/checkopenid
   appid : wxfc498a6955abca31  
   appSecret : 9220bdb59ffe332b23e51d3eed3fbd36

#短信消息配置
aliyunsms:
   accessKeyId : LTAI2DBweLWVhcCB
   secret : cuXJMDuGOhr5O7btkXfSZSjOtnbD3Q
   signName : 智脉科技
   templateCode : SMS_169642214
   msgTemplateCode : SMS_169865398
#使用短消息的模块以及短信注册参数
sms:
   modules: login,project,register,attendance
   register:   
      whilteList:                  
        #允许注册的手机号码，不输入该参数表示全部允许
        #  sql=输入sql语句，语句中包含一个?参数，表示需要查询的号码，存在结果集则允许，否则不允许。
        #  或者输入正则表达式，匹配则允许
      blackList:
        #禁止注册的手机号码，不输入该参数表示全部允许
        #  sql=输入sql语句，语句中包含一个?参数，表示需要查询的号码，存在结果集则禁止，否则允许。
        #  或者输入正则表达式，匹配则禁止
      defaultSql: 
        #设置缺省值参数的sql语句
#reader配置
config:
   D10port: 87     #D10连接的端口地址
   serverIp: 127.0.0.1
   logger:  DEBUG  #DEBUG,ERROR
#   serverurl : http://localhost
   startflag: 1  #启动项目  0:启动所有，1:启动 D10项目， 2:启动锁项目
U53:
   connectUrl: localhost:9000