export default {
  devPeople: {
    title: {
      list: '注册人员列表',
      select: '人员选择',
      record: '注册人员',
      groupDevPeopleRealName: '基本信息',
      groupDevPeopleCardNo: '认证信息',
      sample: '指静脉采集',
      code: '注册人员'
    },
    action: {
      verifyFinger: '验证',
      removeFingerConfirm: '确定要删除该手指的指静脉信息',
      removeFinger: '删除指静脉',
      registerFinger: '注册',
      getRegistered: '已采集',
      syncRegFingersConfirm: '数据异常时后台同步用户注册指静脉数，需要admin权限。确定需要',
      syncRegFingers: '同步注册数',
      sample: '采集指静脉',
      connectDevice: '连接',
      matchFinger: '后端验证',
      resetDevice: '复位'
    },
    route: {
      listTag: '注册人员'
    },
    field: {
      userNoValid: '指静脉唯一识别代码',
      userNo: '用户号',
      realName: '姓名',
      sex: '性别',
      birthDate: '生日',
      orgCode: '部门',
      dutyRank: '职务',
      cardNoValid: '卡号仅支持数字和A-F',
      cardNo: '卡号',
      idType: '证件类型',
      idNumber: '证件号码',
      userType_0: '管理员',
      userType_1: '普通人员',
      userType: '用户类型',
      mobilePhone: '手机号码',
      email: '邮箱',
      registerType: '创建类型',
      validDate: '生效日期',
      expiredDate: '过期日期',
      regTime: '注册时间',
      devPassword: '设备密码',
      regFingers: '注册数',
      note: '备注',
      idNation: '民族',
      photo: '照片',
      homeAddr: '住址',
      fingerNo1_0: '右食指',
      fingerNo1_1: '右中指',
      fingerNo1_2: '右无名指',
      fingerNo1_3: '左食指',
      fingerNo1_4: '左中指',
      fingerNo1_5: '左无名指',
      fingerNo1_6: '自定义1',
      fingerNo1_7: '自定义2',
      fingerNo1: '已采集手指1',
      fingerNo2: '已采集手指2',
      warning1_0: '右食指',
      warning1_1: '右中指',
      warning1_2: '右无名指',
      warning1_3: '左食指',
      warning1_4: '左中指',
      warning1_5: '左无名指',
      warning1_6: '自定义1',
      warning1_7: '自定义2',
      warning1: '胁迫',
      warning2: '胁迫'
    }
  }
}
