export default {
  reader: {
    checkU53: '请检查U53服务',
    u53error: 'U53请求失败',
    resetOK: '复位成功，请等待"滴滴"两声',
    deleteOneFinger: '请先删除一个手指信息',
    noneAuth: '指定手指未注册',
    readFromDevice: '请在设备上读取指静脉',
    authInfo: {
      bytes:'模板字节',
      matches:'匹配数',
      capacity:'模板容量',
      authTimes:'验证时间',
      totalTimes:'合计时间',
      status:'状态码',
      details:'详情',
      score: '分'
    },
    dataDict: {
      dev_access_state_0: '通过',
      dev_access_state_1: '拒绝',
      dev_access_state_2: '胁迫',
      dev_auth_type_1: '指静脉',
      dev_auth_type_2: '卡+指静脉',
      dev_auth_type_3: '卡 或 指静脉',
      dev_auth_type_4: '服务器验证',
      dev_auth_type_5: '密码+指静脉',
      dev_auth_type_6: '密码或指静脉',
      dev_auth_type_7: '密码或指静脉或卡',
      dev_auth_type_8: '指静脉或(卡+密码)',
      dev_mode_MJ: '门禁',
      dev_mode_XG: '巡更',
      dev_mode_AD: '签到',
      dev_mode_ON: '上班',
      dev_mode_OFF: '下班',
      dev_permit_mode_0: '未授权',
      dev_permit_mode_1: '需要审核',
      dev_permit_mode_2: '审核权限',
      dev_permit_mode_4: '授权',
      dev_permit_mode_14: '工作日授权',
      dev_wg_form_3: '自定义',
      dev_wg_out_1: '固定',
      dev_wg_out_2: '编号',
      dev_wg_out_3: '卡号',
      dev_wg_out_4: '区+编号',
      cg_modules_framework: '基本框架',
      cg_modules_codegenerator: '代码生成',
      cg_modules_attendance: '考勤',
      cg_modules_reader: '设备管理',
      cg_modules_svas: '集成服务器验证',
      cg_modules_SvasClient: '验证服务客户端'
    }
  }
}
