-- ----------------------------
-- Table structure for pay_pos
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','PAY_POS','IOTEQU');
CREATE TABLE "IOTEQU"."PAY_POS" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "NO" VARCHAR2(45 BYTE) NOT NULL UNIQUE,
  "SHOP_ID" INTEGER NOT NULL,
  "SECURITY_CODE" VARCHAR2(45 BYTE) NULL,
  "WORK_CODE" VARCHAR2(45 BYTE) NULL,
  "LOGIN_ID" INTEGER NULL,
  "EWALLET_ACTIVE" NUMBER(1) DEFAULT 1 NOT NULL,
  "COUNT_PROJECT_LIST" VARCHAR2(200 BYTE) NULL,
  "TIME_PROJECT_LIST" VARCHAR2(200 BYTE) NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_PAY_POS','IOTEQU');
CREATE SEQUENCE SEQUENCE_PAY_POS;

-- ----------------------------
-- Table structure for pay_operator
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','PAY_OPERATOR','IOTEQU');
CREATE TABLE "IOTEQU"."PAY_OPERATOR" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "NAME" VARCHAR2(45 BYTE) NOT NULL UNIQUE,
  "REAL_NAME" VARCHAR2(45 BYTE) NOT NULL,
  "PASSWORD" VARCHAR2(45 BYTE) NOT NULL,
  "SHOP_ID" INTEGER NOT NULL,
  "USER_NO" VARCHAR2(45 BYTE) NULL UNIQUE
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_PAY_OPERATOR','IOTEQU');
CREATE SEQUENCE SEQUENCE_PAY_OPERATOR;

-- ----------------------------
-- Table structure for pay_shop
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','PAY_SHOP','IOTEQU');
CREATE TABLE "IOTEQU"."PAY_SHOP" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "CORPORATION_ID" INTEGER NOT NULL,
  "NAME" VARCHAR2(45 BYTE) NOT NULL,
  "LINKMAN" VARCHAR2(45 BYTE) NOT NULL,
  "LINK_PHONE" VARCHAR2(45 BYTE) NOT NULL,
  "ADDRESS" VARCHAR2(45 BYTE) NOT NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_PAY_SHOP','IOTEQU');
CREATE SEQUENCE SEQUENCE_PAY_SHOP;

-- ----------------------------
-- Table structure for pay_login
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','PAY_LOGIN','IOTEQU');
CREATE TABLE "IOTEQU"."PAY_LOGIN" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "POS_ID" INTEGER NOT NULL,
  "SHOP_ID" INTEGER NOT NULL,
  "OPERATOR_ID" INTEGER NOT NULL,
  "BATCH_NO" VARCHAR2(45 BYTE) NOT NULL,
  "LOGIN_TIME" DATE NOT NULL,
  "LOGOUT_TIME" DATE NULL,
  "DEVICE_STREAM" VARCHAR2(45 BYTE) NULL,
  "RANDOM_NO" VARCHAR2(45 BYTE) NOT NULL,
  "APP_VERSION" VARCHAR2(45 BYTE) NOT NULL,
  "TRADE_COUNT" INTEGER DEFAULT 0 NOT NULL,
  "FAILURE_COUNT" INTEGER DEFAULT 0 NOT NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_PAY_LOGIN','IOTEQU');
CREATE SEQUENCE SEQUENCE_PAY_LOGIN;

-- ----------------------------
-- Table structure for pay_corporation
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','PAY_CORPORATION','IOTEQU');
CREATE TABLE "IOTEQU"."PAY_CORPORATION" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "PARENT_ID" INTEGER NULL,
  "NAME" VARCHAR2(45 BYTE) NOT NULL,
  "ADDRESS" VARCHAR2(45 BYTE) NOT NULL,
  "LINKMAN" VARCHAR2(45 BYTE) NOT NULL,
  "LINKPHONE" VARCHAR2(45 BYTE) NOT NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_PAY_CORPORATION','IOTEQU');
CREATE SEQUENCE SEQUENCE_PAY_CORPORATION;

ALTER TABLE "IOTEQU"."PAY_POS" ADD CONSTRAINT "IOTEQU"."FK_PAY_POS_SHOP_ID_PAY_SHOP_ID" FOREIGN KEY("SHOP_ID") REFERENCES "IOTEQU"."PAY_SHOP"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "IOTEQU"."PAY_OPERATOR" ADD CONSTRAINT "IOTEQU"."FK_PAY_OPERATOR_SHOP_ID_PAY_SHOP_ID" FOREIGN KEY("SHOP_ID") REFERENCES "IOTEQU"."PAY_SHOP"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "IOTEQU"."PAY_SHOP" ADD CONSTRAINT "IOTEQU"."FK_PAY_SHOP_CORPORATION_ID_PAY_CORPORATION_ID" FOREIGN KEY("CORPORATION_ID") REFERENCES "IOTEQU"."PAY_CORPORATION"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
