-- ----------------------------
-- Table structure for pm_people
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','PM_PEOPLE','IOTEQU');
CREATE TABLE "IOTEQU"."PM_PEOPLE" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "GROUP_ID" INTEGER NOT NULL,
  "USER_ID" VARCHAR2(45 BYTE) NOT NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_PM_PEOPLE','IOTEQU');
CREATE SEQUENCE SEQUENCE_PM_PEOPLE;

ALTER TABLE "IOTEQU"."PM_PEOPLE" ADD CONSTRAINT  "UI_PM_PEOPLE01" UNIQUE ("GROUP_ID","USER_ID");
-- ----------------------------
-- Table structure for pm_version_application
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','PM_VERSION_APPLICATION','IOTEQU');
CREATE TABLE "IOTEQU"."PM_VERSION_APPLICATION" (
  "ID" CHAR(32) NOT NULL PRIMARY KEY,
  "FLOW_STATE" INTEGER DEFAULT 1 NOT NULL,
  "FLOW_REGISTER_TIME" DATE NOT NULL,
  "FLOW_REGISTER_BY" VARCHAR2(45 BYTE) NOT NULL,
  "PROJECT" VARCHAR2(36 BYTE) NOT NULL,
  "APPLICATION_TYPE" INTEGER NOT NULL,
  "CUSTOMER" VARCHAR2(20 BYTE) NOT NULL,
  "LICENCE" VARCHAR2(100 BYTE) NOT NULL,
  "CONTRACT_NO" VARCHAR2(45 BYTE) NULL,
  "DESCRIPTION" VARCHAR2(200 BYTE) NOT NULL,
  "VERSION_INFO" VARCHAR2(200 BYTE) NULL,
  "FLOW_NOTE" VARCHAR2(1000 BYTE) NULL,
  "ADD_FILE" VARCHAR2(200 BYTE) NULL,
  "FLOW_NEXT_OPERATOR" VARCHAR2(45 BYTE) NULL,
  "FLOW_COPY_TO_LIST" VARCHAR2(100 BYTE) NULL
);
CALL REMOVE_OBJECT('INDEX','INDEX_PM_VERSION_APPLICATION_PROJECT','IOTEQU');
CREATE INDEX "IOTEQU"."INDEX_PM_VERSION_APPLICATION_PROJECT" ON "IOTEQU"."PM_VERSION_APPLICATION"("PROJECT");

-- ----------------------------
-- Table structure for pm_project
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','PM_PROJECT','IOTEQU');
CREATE TABLE "IOTEQU"."PM_PROJECT" (
  "ID" CHAR(32) NOT NULL PRIMARY KEY,
  "FLOW_STATE" INTEGER DEFAULT 1 NOT NULL,
  "FLOW_REGISTER_TIME" DATE NOT NULL,
  "FLOW_REGISTER_BY" VARCHAR2(45 BYTE) NOT NULL,
  "NAME" VARCHAR2(45 BYTE) NOT NULL UNIQUE,
  "TYPE" INTEGER DEFAULT 1 NOT NULL,
  "CUSTOMER" VARCHAR2(200 BYTE) NULL,
  "MARKET_SIZE" INTEGER NULL,
  "HUMAN_COST" INTEGER NULL,
  "MATERIAL_COST" INTEGER NULL,
  "CODE" VARCHAR2(45 BYTE) NULL UNIQUE,
  "DESCRIPTION" VARCHAR2(500 BYTE) NULL,
  "FLOW_NOTE" VARCHAR2(1000 BYTE) NULL,
  "ADD_FILE" VARCHAR2(45 BYTE) NULL,
  "FLOW_NEXT_OPERATOR" VARCHAR2(45 BYTE) NULL,
  "FLOW_COPY_TO_LIST" VARCHAR2(100 BYTE) NULL
);

-- ----------------------------
-- Table structure for pm_people_group
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','PM_PEOPLE_GROUP','IOTEQU');
CREATE TABLE "IOTEQU"."PM_PEOPLE_GROUP" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "PARENT" INTEGER NULL,
  "NAME" VARCHAR2(45 BYTE) NOT NULL,
  "GROUP_TYPE" VARCHAR2(45 BYTE) NOT NULL UNIQUE,
  "ENABLED" NUMBER(1) DEFAULT 1 NOT NULL,
  "DESCRIPTION" VARCHAR2(200 BYTE) NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_PM_PEOPLE_GROUP','IOTEQU');
CREATE SEQUENCE SEQUENCE_PM_PEOPLE_GROUP;

ALTER TABLE "IOTEQU"."PM_PEOPLE" ADD CONSTRAINT "IOTEQU"."FK_PM_PEOPLE_GROUP_ID_PM_PEOPLE_GROUP_ID" FOREIGN KEY("GROUP_ID") REFERENCES "IOTEQU"."PM_PEOPLE_GROUP"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
