export default {
  devReader: {
    title: {
      list: 'devReader',
      record: 'devReader',
      groupDevReaderName: 'groupDevReaderName',
      groupDevReaderAlignMethod: 'groupDevReaderAlignMethod',
      groupDevReaderWgOrder: 'groupDevReaderWgOrder',
      code: 'DevReader'
    },
    action: {
      selectParam: 'SelectParam',
      queryTime: 'QueryTime',
      setDeviceTime: 'SetDeviceTime',
      resetDeviceConfirm: 'Confirm ResetDevice',
      resetDevice: 'ResetDevice',
      data: 'Data',
      deleteAllUsersConfirm: 'Confirm DeleteAllUsers',
      deleteAllUsers: 'DeleteAllUsers',
      reportPeople: 'ReportPeople'
    },
    route: {
      listTag: 'devReader',
      recordTag: 'devReader'
    },
    field: {
      id: 'Id',
      readerNo: 'ReaderNo',
      name: 'Name',
      type: 'Type',
      readerGroup: 'ReaderGroup',
      address: 'Address',
      connectType: 'ConnectType',
      ip: 'Ip',
      snNo: 'SnNo',
      devMode: 'DevMode',
      firmware: 'Firmware',
      isOnline: 'IsOnline',
      isTimeSyncValid: 'Please input correct value for isTimeSync',
      isTimeSync: 'IsTimeSync',
      alignMethod: 'AlignMethod',
      blacklightTime_0: '10s',
      blacklightTime_1: '30s',
      blacklightTime_2: '60s',
      blacklightTime_3: '90s',
      blacklightTime_4: '常亮',
      blacklightTime: 'BlacklightTime',
      voiceprompt: 'Voiceprompt',
      menuTime_0: '10s',
      menuTime_1: '30s',
      menuTime_2: '60s',
      menuTime_3: '90s',
      menuTime: 'MenuTime',
      wengenform: 'Wengenform',
      wengenOutput: 'WengenOutput',
      wengenOutArea: 'WengenOutArea',
      regfingerOutTime: 'RegfingerOutTime',
      authfingerOutTime: 'AuthfingerOutTime',
      wgOrder_0: '低位先发',
      wgOrder_1: '高位先发',
      wgOrder: 'WgOrder',
      relayTimeValid: 'Please input correct value for relayTime',
      relayTime: 'RelayTime',
      fixedValueValid: 'Please input correct value for fixedValue',
      fixedValue: 'FixedValue',
      alarmEnable_0: '关闭',
      alarmEnable_1: '开启',
      alarmEnable: 'AlarmEnable',
      openEnable_0: '关闭',
      openEnable_1: '开启',
      openEnable: 'OpenEnable',
      doorState_0: '关闭',
      doorState_1: '开启',
      doorState: 'DoorState',
      relayEnable_0: '关闭',
      relayEnable_1: '开启',
      relayEnable: 'RelayEnable',
      doorbellEnable_0: '关闭',
      doorbellEnable_1: '开启',
      doorbellEnable: 'DoorbellEnable',
      wifiSsid: 'WifiSsid',
      wifiPsw: 'WifiPsw'
    }
  }
}
