export default {
  devReader: {
    title: {
      list: 'Device',
      record: 'Device',
      groupDevReaderName: 'Device setting',
      groupDevReaderAlignMethod: 'Device paramaters',
      groupDevReaderWgOrder: 'D30 extends',
      code: 'Device'
    },
    action: {
      readerOnline: 'Reader online',
      selectParam: 'Select param',
      queryTime: 'Query time',
      setDeviceTime: 'Set device time',
      resetDeviceConfirm: 'Confirm reset device',
      resetDevice: 'Reset device',
      data: 'Data',
      deleteAllUsersConfirm: 'Confirm delete all users',
      deleteAllUsers: 'Delete all users',
      reportPeople: 'Report people',
      againDownload: 'Again download'
    },
    field: {
      id: 'Id',
      readerNo: 'Reader no',
      name: 'Name',
      type: 'Type',
      readerGroup: 'Reader group',
      address: 'Address',
      capacity: 'Capacity',
      connectType: 'Connect type',
      ip: 'Ip',
      snNo: 'Sn no',
      devMode: 'Dev mode',
      firmware: 'Firmware',
      isOnline: 'Is online',
      isTimeSyncValid: 'Please input correct value for is time sync',
      isTimeSync: 'Is time sync',
      alignMethod: 'Align method',
      blacklightTime_0: '10s',
      blacklightTime_1: '30s',
      blacklightTime_2: '60s',
      blacklightTime_3: '90s',
      blacklightTime_4: 'Always',
      blacklightTime: 'Blacklight time',
      voiceprompt: 'Voiceprompt',
      menuTime_0: '10s',
      menuTime_1: '30s',
      menuTime_2: '60s',
      menuTime_3: '90s',
      menuTime: 'Menu time',
      wengenform: 'Wengenform',
      wengenOutput: 'Wengen output',
      wengenOutArea: 'Wengen out area',
      regfingerOutTime: 'Regfinger out time',
      authfingerOutTime: 'Authfinger out time',
      wgOrder_0: 'Little endian',
      wgOrder_1: 'Big endian',
      wgOrder: 'Wg order',
      relayTimeValid: 'Please input correct value for relay time',
      relayTime: 'Relay time',
      fixedValueValid: 'Please input correct value for fixed value',
      fixedValue: 'Fixed value',
      alarmEnable_0: 'Off',
      alarmEnable_1: 'On',
      alarmEnable: 'Alarm enable',
      openEnable_0: 'Off',
      openEnable_1: 'On',
      openEnable: 'Open enable',
      doorState_0: 'Off',
      doorState_1: 'On',
      doorState: 'Door state',
      relayEnable_0: 'Off',
      relayEnable_1: 'On',
      relayEnable: 'Relay enable',
      doorbellEnable_0: 'Off',
      doorbellEnable_1: 'On',
      doorbellEnable: 'Doorbell enable',
      wifiSsid: 'Wifi ssid',
      wifiPsw: 'Wifi password'
    }
  }
}
