-- ----------------------------
-- Table structure for ew_user_time
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','EW_USER_TIME','IOTEQU');
CREATE TABLE "IOTEQU"."EW_USER_TIME" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "USER_NO" VARCHAR2(45 BYTE) NOT NULL,
  "TIME_ID" INTEGER NOT NULL,
  "AMOUNT_TIME" INTEGER DEFAULT 0 NOT NULL,
  "CHECK_CODE" VARCHAR2(45 BYTE) NOT NULL,
  "COST_LIMIT" INTEGER DEFAULT 0 NOT NULL,
  "DAY_LIMIT" INTEGER DEFAULT 0 NOT NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_EW_USER_TIME','IOTEQU');
CREATE SEQUENCE SEQUENCE_EW_USER_TIME;

ALTER TABLE "IOTEQU"."EW_USER_TIME" ADD CONSTRAINT  "UI_EW_USER_TIME01" UNIQUE ("USER_NO","TIME_ID");
-- ----------------------------
-- Table structure for ew_user_count
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','EW_USER_COUNT','IOTEQU');
CREATE TABLE "IOTEQU"."EW_USER_COUNT" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "USER_NO" VARCHAR2(45 BYTE) NOT NULL,
  "COUNT_ID" INTEGER NOT NULL,
  "AMOUNT_COUNT" INTEGER DEFAULT 0 NOT NULL,
  "CHECK_CODE" VARCHAR2(45 BYTE) NOT NULL,
  "COST_LIMIT" INTEGER DEFAULT 0 NOT NULL,
  "DAY_LIMIT" INTEGER DEFAULT 0 NOT NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_EW_USER_COUNT','IOTEQU');
CREATE SEQUENCE SEQUENCE_EW_USER_COUNT;

ALTER TABLE "IOTEQU"."EW_USER_COUNT" ADD CONSTRAINT  "UI_EW_USER_COUNT01" UNIQUE ("USER_NO","COUNT_ID");
-- ----------------------------
-- Table structure for ew_user
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','EW_USER','IOTEQU');
CREATE TABLE "IOTEQU"."EW_USER" (
  "USER_NO" VARCHAR2(32 BYTE) NOT NULL PRIMARY KEY,
  "IS_ACTIVE" NUMBER(1) DEFAULT 1 NULL,
  "NAME" VARCHAR2(32 BYTE) NOT NULL,
  "GENDER" INTEGER NOT NULL,
  "ID_TYPE" INTEGER NOT NULL,
  "ID_NO" VARCHAR2(45 BYTE) NOT NULL,
  "MOBILE_PHONE" VARCHAR2(45 BYTE) NULL UNIQUE,
  "EMAIL" VARCHAR2(45 BYTE) NULL UNIQUE,
  "WECHAT_OPENID" VARCHAR2(45 BYTE) NULL UNIQUE,
  "BIRTH_DATE" DATE NULL,
  "MEMBER_GROUP" VARCHAR2(45 BYTE) NULL,
  "BONUS_POINT" INTEGER DEFAULT 0 NOT NULL,
  "AMOUNT_MONEY" INTEGER DEFAULT 0 NOT NULL,
  "COST_LIMIT" INTEGER DEFAULT 0 NOT NULL,
  "DAY_LIMIT" INTEGER DEFAULT 0 NOT NULL,
  "ACTIVE_SINCE" DATE NULL,
  "EXPIRE_AT" DATE NULL,
  "CHECK_CODE" VARCHAR2(45 BYTE) NOT NULL
);

-- ----------------------------
-- Table structure for ew_time_project
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','EW_TIME_PROJECT','IOTEQU');
CREATE TABLE "IOTEQU"."EW_TIME_PROJECT" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "ICON" VARCHAR2(45 BYTE) NULL,
  "NAME" VARCHAR2(45 BYTE) NOT NULL,
  "BASE_VALUE" INTEGER DEFAULT 60 NOT NULL,
  "BASE_PRICE" INTEGER DEFAULT 10 NOT NULL,
  "BONUS_POINT" NUMBER(12:2) NOT NULL,
  "START_TIME" DATE NULL,
  "END_TIME" DATE NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_EW_TIME_PROJECT','IOTEQU');
CREATE SEQUENCE SEQUENCE_EW_TIME_PROJECT;

-- ----------------------------
-- Table structure for ew_device
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','EW_DEVICE','IOTEQU');
CREATE TABLE "IOTEQU"."EW_DEVICE" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "DEVICE_NO" VARCHAR2(45 BYTE) NOT NULL,
  "SHOP_ID" VARCHAR2(45 BYTE) NOT NULL,
  "PRIVILEGE_LIST" VARCHAR2(64 BYTE) NOT NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_EW_DEVICE','IOTEQU');
CREATE SEQUENCE SEQUENCE_EW_DEVICE;

-- ----------------------------
-- Table structure for ew_count_project
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','EW_COUNT_PROJECT','IOTEQU');
CREATE TABLE "IOTEQU"."EW_COUNT_PROJECT" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "ICON" VARCHAR2(45 BYTE) NULL,
  "NAME" VARCHAR2(45 BYTE) NOT NULL,
  "BASE_PRICE" INTEGER DEFAULT 10 NOT NULL,
  "BASE_VALUE" INTEGER DEFAULT 1 NOT NULL,
  "BONUS_POINT" NUMBER(12:2) NOT NULL,
  "START_TIME" DATE NULL,
  "END_TIME" DATE NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_EW_COUNT_PROJECT','IOTEQU');
CREATE SEQUENCE SEQUENCE_EW_COUNT_PROJECT;

-- ----------------------------
-- Table structure for ew_bill
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','EW_BILL','IOTEQU');
CREATE TABLE "IOTEQU"."EW_BILL" (
  "NO" VARCHAR2(32 BYTE) NOT NULL PRIMARY KEY,
  "CANCELED" NUMBER(1) DEFAULT 0 NOT NULL,
  "IS_CHARGE" NUMBER(1) DEFAULT 0 NOT NULL,
  "USER_NO" VARCHAR2(45 BYTE) NOT NULL,
  "BATCH_NO" VARCHAR2(45 BYTE) NOT NULL,
  "DT" DATE NOT NULL,
  "OPERATION_TYPE" INTEGER NOT NULL,
  "COST_TYPE" INTEGER DEFAULT 1 NOT NULL,
  "PROJECT_ID" INTEGER DEFAULT 0 NOT NULL,
  "PROJECT_NAME" VARCHAR2(45 BYTE) DEFAULT '消费' NOT NULL,
  "PROJECT_PRICE" INTEGER NOT NULL,
  "AMOUNT" INTEGER NOT NULL,
  "AMOUNT_BEFORE" INTEGER NOT NULL,
  "BONUS" INTEGER NOT NULL,
  "BONUS_BEFORE" INTEGER NOT NULL,
  "DEVICE_NO" VARCHAR2(45 BYTE) NOT NULL,
  "SHOP_ID" VARCHAR2(45 BYTE) NOT NULL,
  "DEVICE_STREAM" VARCHAR2(45 BYTE) NOT NULL,
  "DEVICE_DT" DATE NOT NULL,
  "TRADE_NO" VARCHAR2(45 BYTE) NOT NULL UNIQUE,
  "OPERATOR_NO" VARCHAR2(45 BYTE) NOT NULL,
  "CHECK_CODE" VARCHAR2(45 BYTE) NOT NULL,
  "LINK_NO" VARCHAR2(45 BYTE) NULL,
  "LOGIN_ID" INTEGER NOT NULL
);
CALL REMOVE_OBJECT('INDEX','INDEX_EW_BILL_IS_CHARGE','IOTEQU');
CREATE INDEX "IOTEQU"."INDEX_EW_BILL_IS_CHARGE" ON "IOTEQU"."EW_BILL"("IS_CHARGE");
CALL REMOVE_OBJECT('INDEX','INDEX_EW_BILL_USER_NO','IOTEQU');
CREATE INDEX "IOTEQU"."INDEX_EW_BILL_USER_NO" ON "IOTEQU"."EW_BILL"("USER_NO");
CALL REMOVE_OBJECT('INDEX','INDEX_EW_BILL_DT','IOTEQU');
CREATE INDEX "IOTEQU"."INDEX_EW_BILL_DT" ON "IOTEQU"."EW_BILL"("DT");
CALL REMOVE_OBJECT('INDEX','INDEX_EW_BILL_COST_TYPE','IOTEQU');
CREATE INDEX "IOTEQU"."INDEX_EW_BILL_COST_TYPE" ON "IOTEQU"."EW_BILL"("COST_TYPE");
CALL REMOVE_OBJECT('INDEX','INDEX_EW_BILL_PROJECT_ID','IOTEQU');
CREATE INDEX "IOTEQU"."INDEX_EW_BILL_PROJECT_ID" ON "IOTEQU"."EW_BILL"("PROJECT_ID");
CALL REMOVE_OBJECT('INDEX','INDEX_EW_BILL_SHOP_ID','IOTEQU');
CREATE INDEX "IOTEQU"."INDEX_EW_BILL_SHOP_ID" ON "IOTEQU"."EW_BILL"("SHOP_ID");
CALL REMOVE_OBJECT('INDEX','INDEX_EW_BILL_OPERATOR_NO','IOTEQU');
CREATE INDEX "IOTEQU"."INDEX_EW_BILL_OPERATOR_NO" ON "IOTEQU"."EW_BILL"("OPERATOR_NO");
CALL REMOVE_OBJECT('INDEX','INDEX_EW_BILL_LOGIN_ID','IOTEQU');
CREATE INDEX "IOTEQU"."INDEX_EW_BILL_LOGIN_ID" ON "IOTEQU"."EW_BILL"("LOGIN_ID");

ALTER TABLE "IOTEQU"."EW_USER_TIME" ADD CONSTRAINT "IOTEQU"."FK_EW_USER_TIME_USER_NO_EW_USER_USER_NO" FOREIGN KEY("USER_NO") REFERENCES "IOTEQU"."EW_USER"("USER_NO") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "IOTEQU"."EW_USER_TIME" ADD CONSTRAINT "IOTEQU"."FK_EW_USER_TIME_TIME_ID_EW_TIME_PROJECT_ID" FOREIGN KEY("TIME_ID") REFERENCES "IOTEQU"."EW_TIME_PROJECT"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "IOTEQU"."EW_USER_COUNT" ADD CONSTRAINT "IOTEQU"."FK_EW_USER_COUNT_USER_NO_EW_USER_USER_NO" FOREIGN KEY("USER_NO") REFERENCES "IOTEQU"."EW_USER"("USER_NO") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "IOTEQU"."EW_USER_COUNT" ADD CONSTRAINT "IOTEQU"."FK_EW_USER_COUNT_COUNT_ID_EW_COUNT_PROJECT_ID" FOREIGN KEY("COUNT_ID") REFERENCES "IOTEQU"."EW_COUNT_PROJECT"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
