-- ----------------------------
-- Table structure for ck_register
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','CK_REGISTER','IOTEQU');
CREATE TABLE "IOTEQU"."CK_REGISTER" (
  "ID" CHAR(32) NOT NULL PRIMARY KEY,
  "USER_NO" VARCHAR2(36 BYTE) NOT NULL,
  "NAME" VARCHAR2(32 BYTE) NOT NULL,
  "SEX" VARCHAR2(1 BYTE) DEFAULT '1' NOT NULL,
  "BIRTH_DATE" DATE NULL,
  "ORG_CODE" INTEGER NOT NULL,
  "ORG_NAME" VARCHAR2(32 BYTE) NOT NULL,
  "IN_DATE" DATE NOT NULL,
  "ON_TIME" DATE NOT NULL,
  "OFF_TIME" DATE NULL
);

ALTER TABLE "IOTEQU"."CK_REGISTER" ADD CONSTRAINT  "UI_CK_REGISTER012" UNIQUE ("USER_NO","ORG_CODE","IN_DATE");
