-- ----------------------------
-- Table structure for sys_user
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','SYS_USER','IOTEQU');
CREATE TABLE "IOTEQU"."SYS_USER" (
  "ID" VARCHAR2(32 BYTE) NOT NULL PRIMARY KEY,
  "ICON" CLOB NULL,
  "NAME" VARCHAR2(32 BYTE) NOT NULL UNIQUE,
  "REAL_NAME" VARCHAR2(32 BYTE) NOT NULL,
  "SEX" VARCHAR2(1 BYTE) DEFAULT '1' NULL,
  "BIRTH_DATE" DATE NULL,
  "REG_TIME" DATE NULL,
  "MOBILE_PHONE" VARCHAR2(32 BYTE) NULL UNIQUE,
  "EMAIL" VARCHAR2(50 BYTE) NULL UNIQUE,
  "WECHAT_OPENID" VARCHAR2(50 BYTE) NULL UNIQUE,
  "ORG_CODE" INTEGER NOT NULL,
  "ORG_PRIVILEGE" INTEGER NULL,
  "ROLE_LIST" VARCHAR2(200 BYTE) NULL,
  "LOCKED" NUMBER(1) DEFAULT 0 NOT NULL,
  "STATE" NUMBER(1) DEFAULT 1 NOT NULL,
  "ID_TYPE" INTEGER DEFAULT 1 NOT NULL,
  "ID_NUMBER" VARCHAR2(45 BYTE) NOT NULL,
  "EXPIRED_TIME" DATE NULL,
  "PASSWORD_EXPIRED_TIME" DATE NULL,
  "PASSWORD" VARCHAR2(32 BYTE) DEFAULT '123456' NOT NULL,
  "PASSWORD_ERROR_TIMES" INTEGER DEFAULT 0 NOT NULL
);
CALL REMOVE_OBJECT('INDEX','INDEX_SYS_USER_ORG_CODE','IOTEQU');
CREATE INDEX "IOTEQU"."INDEX_SYS_USER_ORG_CODE" ON "IOTEQU"."SYS_USER"("ORG_CODE");

ALTER TABLE "IOTEQU"."SYS_USER" ADD CONSTRAINT  "UI_SYS_USER01" UNIQUE ("ID_TYPE","ID_NUMBER");
-- ----------------------------
-- Table structure for sys_task
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','SYS_TASK','IOTEQU');
CREATE TABLE "IOTEQU"."SYS_TASK" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "NAME" VARCHAR2(45 BYTE) NOT NULL,
  "DESCRIPTION" VARCHAR2(300 BYTE) NULL,
  "SCEDULE_YEARS" VARCHAR2(100 BYTE) DEFAULT '*' NOT NULL,
  "SCHEDULE_MONTHS" VARCHAR2(100 BYTE) DEFAULT '*' NOT NULL,
  "SCHEDULE_DAYS" VARCHAR2(100 BYTE) DEFAULT '*' NOT NULL,
  "SCHEDULE_WEEKS" VARCHAR2(100 BYTE) DEFAULT '*' NOT NULL,
  "SCHEDULE_HOURS" VARCHAR2(100 BYTE) DEFAULT '*' NOT NULL,
  "SCHEDULE_MINUTES" VARCHAR2(100 BYTE) DEFAULT '*' NOT NULL,
  "CLASS_NAME" VARCHAR2(100 BYTE) NOT NULL,
  "MOTHOD_NAME" VARCHAR2(500 BYTE) NOT NULL,
  "IS_STATIC" NUMBER(1) DEFAULT 1 NOT NULL,
  "PARAMES" VARCHAR2(100 BYTE) NULL,
  "IS_RUNNING" NUMBER(1) DEFAULT 1 NOT NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_SYS_TASK','IOTEQU');
CREATE SEQUENCE SEQUENCE_SYS_TASK;

-- ----------------------------
-- Table structure for sys_route
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','SYS_ROUTE','IOTEQU');
CREATE TABLE "IOTEQU"."SYS_ROUTE" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "PATH" VARCHAR2(200 BYTE) NOT NULL UNIQUE,
  "NAME" VARCHAR2(100 BYTE) NOT NULL UNIQUE,
  "COMPONENT" VARCHAR2(200 BYTE) DEFAULT 'Layout' NOT NULL,
  "TITLE" VARCHAR2(100 BYTE) NOT NULL,
  "BREADCRUMB_SHOW" NUMBER(1) DEFAULT 1 NOT NULL,
  "NEED_CACHE" NUMBER(1) DEFAULT 1 NOT NULL,
  "TAG_VIEW" NUMBER(1) DEFAULT 1 NOT NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_SYS_ROUTE','IOTEQU');
CREATE SEQUENCE SEQUENCE_SYS_ROUTE;

-- ----------------------------
-- Table structure for sys_role
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','SYS_ROLE','IOTEQU');
CREATE TABLE "IOTEQU"."SYS_ROLE" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "CODE" VARCHAR2(8 BYTE) NOT NULL UNIQUE,
  "NAME" VARCHAR2(45 BYTE) NOT NULL UNIQUE,
  "NOTE" VARCHAR2(64 BYTE) NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_SYS_ROLE','IOTEQU');
CREATE SEQUENCE SEQUENCE_SYS_ROLE;

-- ----------------------------
-- Table structure for sys_permission
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','SYS_PERMISSION','IOTEQU');
CREATE TABLE "IOTEQU"."SYS_PERMISSION" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "ROLE" INTEGER NOT NULL,
  "ACTION" INTEGER NOT NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_SYS_PERMISSION','IOTEQU');
CREATE SEQUENCE SEQUENCE_SYS_PERMISSION;
CALL REMOVE_OBJECT('INDEX','INDEX_SYS_PERMISSION_ROLE','IOTEQU');
CREATE INDEX "IOTEQU"."INDEX_SYS_PERMISSION_ROLE" ON "IOTEQU"."SYS_PERMISSION"("ROLE");
CALL REMOVE_OBJECT('INDEX','INDEX_SYS_PERMISSION_ACTION','IOTEQU');
CREATE INDEX "IOTEQU"."INDEX_SYS_PERMISSION_ACTION" ON "IOTEQU"."SYS_PERMISSION"("ACTION");

-- ----------------------------
-- Table structure for sys_org
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','SYS_ORG','IOTEQU');
CREATE TABLE "IOTEQU"."SYS_ORG" (
  "ORG_CODE" INTEGER NOT NULL PRIMARY KEY,
  "NAME" VARCHAR2(32 BYTE) NOT NULL,
  "PARENT" INTEGER NULL,
  "PHONE" VARCHAR2(32 BYTE) NULL,
  "FAX" VARCHAR2(32 BYTE) NULL,
  "ROLE_LIST" VARCHAR2(200 BYTE) NULL,
  "ADDRESS" VARCHAR2(100 BYTE) NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_SYS_ORG','IOTEQU');
CREATE SEQUENCE SEQUENCE_SYS_ORG;

ALTER TABLE "IOTEQU"."SYS_ORG" ADD CONSTRAINT  "UI_SYS_ORG01" UNIQUE ("NAME","PARENT");
-- ----------------------------
-- Table structure for sys_message
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','SYS_MESSAGE','IOTEQU');
CREATE TABLE "IOTEQU"."SYS_MESSAGE" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "READ_TIME" DATE NULL,
  "CREATE_TIME" DATE NOT NULL,
  "RECEIVER_NAME" VARCHAR2(50 BYTE) NULL,
  "SENDER_NAME" VARCHAR2(50 BYTE) NULL,
  "TITLE" VARCHAR2(100 BYTE) NOT NULL,
  "CONTENT" CLOB NOT NULL,
  "URL" VARCHAR2(100 BYTE) NULL,
  "RECEIVER" VARCHAR2(50 BYTE) NULL,
  "SENDER" VARCHAR2(100 BYTE) NULL,
  "EVENT_ID" VARCHAR2(45 BYTE) NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_SYS_MESSAGE','IOTEQU');
CREATE SEQUENCE SEQUENCE_SYS_MESSAGE;

-- ----------------------------
-- Table structure for sys_menu
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','SYS_MENU','IOTEQU');
CREATE TABLE "IOTEQU"."SYS_MENU" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "SORT_NUM" INTEGER DEFAULT 10 NOT NULL,
  "NAME" VARCHAR2(45 BYTE) NOT NULL,
  "PARENT" INTEGER NULL,
  "IS_DIVIDER" NUMBER(1) DEFAULT 0 NOT NULL,
  "ICON" VARCHAR2(50 BYTE) NULL,
  "ACTION" VARCHAR2(100 BYTE) NULL,
  "CLASS_NAME" VARCHAR2(45 BYTE) NULL,
  "DATA_ACTION" VARCHAR2(200 BYTE) NULL,
  "BIGICON" VARCHAR2(50 BYTE) NULL,
  "MOBILE_HIDDEN" NUMBER(1) DEFAULT 0 NOT NULL,
  "JS_CMD" VARCHAR2(45 BYTE) NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_SYS_MENU','IOTEQU');
CREATE SEQUENCE SEQUENCE_SYS_MENU;

ALTER TABLE "IOTEQU"."SYS_MENU" ADD CONSTRAINT  "UI_SYS_MENU012" UNIQUE ("NAME","PARENT","ACTION");
-- ----------------------------
-- Table structure for sys_log
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','SYS_LOG','IOTEQU');
CREATE TABLE "IOTEQU"."SYS_LOG" (
  "ID" CHAR(32) NOT NULL PRIMARY KEY,
  "TIME" DATE NOT NULL,
  "KEYWORD" VARCHAR2(100 BYTE) NOT NULL,
  "USER_TYPE" VARCHAR2(64 BYTE) NULL,
  "USER_INFO" VARCHAR2(64 BYTE) NULL,
  "NOTE" VARCHAR2(1000 BYTE) NULL
);

-- ----------------------------
-- Table structure for sys_flow_process
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','SYS_FLOW_PROCESS','IOTEQU');
CREATE TABLE "IOTEQU"."SYS_FLOW_PROCESS" (
  "ID" CHAR(32) NOT NULL PRIMARY KEY,
  "FLOW_ID" VARCHAR2(36 BYTE) NOT NULL,
  "OPERATION" VARCHAR2(36 BYTE) NULL,
  "SELECTION" VARCHAR2(36 BYTE) NULL,
  "STATE_NAME0" VARCHAR2(45 BYTE) NULL,
  "STATE_NAME1" VARCHAR2(45 BYTE) NULL,
  "OPERATOR" VARCHAR2(36 BYTE) NOT NULL,
  "TIME" DATE NOT NULL,
  "NOTE" VARCHAR2(200 BYTE) NULL,
  "NEXT_OPERATOR" VARCHAR2(45 BYTE) NULL,
  "STATE0" INTEGER NULL,
  "STATE1" INTEGER NOT NULL
);

-- ----------------------------
-- Table structure for sys_data_dict
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','SYS_DATA_DICT','IOTEQU');
CREATE TABLE "IOTEQU"."SYS_DATA_DICT" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "DICT" VARCHAR2(45 BYTE) NOT NULL,
  "CODE" VARCHAR2(45 BYTE) NOT NULL,
  "TEXT" VARCHAR2(100 BYTE) NOT NULL,
  "ORDER_NUM" INTEGER NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_SYS_DATA_DICT','IOTEQU');
CREATE SEQUENCE SEQUENCE_SYS_DATA_DICT;

ALTER TABLE "IOTEQU"."SYS_DATA_DICT" ADD CONSTRAINT  "UI_SYS_DATA_DICT01" UNIQUE ("DICT","CODE");
-- ----------------------------
-- Table structure for sys_action
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','SYS_ACTION','IOTEQU');
CREATE TABLE "IOTEQU"."SYS_ACTION" (
  "NOTE" VARCHAR2(200 BYTE) NULL,
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "VALUE" VARCHAR2(100 BYTE) NOT NULL,
  "PARAMS" VARCHAR2(100 BYTE) NULL,
  "METHOD" VARCHAR2(45 BYTE) NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_SYS_ACTION','IOTEQU');
CREATE SEQUENCE SEQUENCE_SYS_ACTION;
CALL REMOVE_OBJECT('INDEX','INDEX_SYS_ACTION_VALUE','IOTEQU');
CREATE INDEX "IOTEQU"."INDEX_SYS_ACTION_VALUE" ON "IOTEQU"."SYS_ACTION"("VALUE");

-- ----------------------------
-- Table structure for oauth_client_details
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','OAUTH_CLIENT_DETAILS','IOTEQU');
CREATE TABLE "IOTEQU"."OAUTH_CLIENT_DETAILS" (
  "CLIENT_ID" VARCHAR2(255 BYTE) NOT NULL PRIMARY KEY,
  "CLIENT_SECRET" VARCHAR2(255 BYTE) NOT NULL,
  "SCOPE" VARCHAR2(255 BYTE) NOT NULL,
  "AUTHORIZED_GRANT_TYPES" VARCHAR2(255 BYTE) NOT NULL,
  "WEB_SERVER_REDIRECT_URI" VARCHAR2(255 BYTE) NULL,
  "AUTHORITIES" VARCHAR2(255 BYTE) NOT NULL,
  "ACCESS_TOKEN_VALIDITY" INTEGER DEFAULT 86400 NOT NULL,
  "REFRESH_TOKEN_VALIDITY" INTEGER DEFAULT 0 NOT NULL,
  "AUTOAPPROVE" VARCHAR2(20 BYTE) DEFAULT '1' NOT NULL,
  "EXPIRED_DATE" DATE NULL,
  "LOCKED" NUMBER(1) DEFAULT 0 NOT NULL,
  "ENABLED" NUMBER(1) DEFAULT 1 NOT NULL,
  "DECRIPTION" VARCHAR2(200 BYTE) NULL,
  "ADDITIONAL_INFORMATION" CLOB NULL,
  "RESOURCE_IDS" VARCHAR2(255 BYTE) NULL
);

