-- ----------------------------
-- Table structure for pm_people_group
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','PM_PEOPLE_GROUP','IOTEQU');
CREATE TABLE "IOTEQU"."PM_PEOPLE_GROUP" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "PARENT" INTEGER NULL,
  "NAME" VARCHAR2(45 BYTE) NOT NULL,
  "GROUP_TYPE" VARCHAR2(45 BYTE) NOT NULL UNIQUE,
  "ENABLED" NUMBER(1) DEFAULT 1 NOT NULL,
  "DESCRIPTION" VARCHAR2(200 BYTE) NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_PM_PEOPLE_GROUP','IOTEQU');
CREATE SEQUENCE SEQUENCE_PM_PEOPLE_GROUP;

