export default {
  cgField: {
    title: {
      list: 'cgField',
      record: 'cgField',
      groupCgFieldTitle: 'groupCgFieldTitle',
      groupCgFieldDictTable: 'groupCgFieldDictTable',
      groupCgFieldType: 'groupCgFieldType',
      code: 'CgField'
    },
    action: {
      extDict: 'ExtDict'
    },
    route: {
      listTag: 'cgField',
      recordTag: 'cgField'
    },
    field: {
      id: 'Id',
      tableIdValid: 'Please input correct value for tableId',
      tableId: 'TableId',
      orderNumValid: 'Please input correct value for orderNum',
      orderNum: 'OrderNum',
      entityNameValid: 'Please input correct value for entityName',
      entityName: 'EntityName',
      titleValid: 'Please input correct value for title',
      title: 'Title',
      nameValid: 'Please input correct value for name',
      name: 'Name',
      keyTypeValid: 'Please input correct value for keyType',
      keyType_0: '无',
      keyType_1: '自增长主键',
      keyType_2: 'uuid主键',
      keyType_3: '普通主键',
      keyType_4: '唯一索引',
      keyType_5: '非唯一索引',
      keyType_6: '联合唯一索引1',
      keyType_7: '联合唯一索引2',
      keyType_8: '联合唯一索引3',
      keyType: 'KeyType',
      defaultValueValid: 'Please input correct value for defaultValue',
      defaultValue: 'DefaultValue',
      showTypeValid: 'Please input correct value for showType',
      showType_0: '',
      showType_1: '',
      showType_2: '',
      showType_3: '',
      showType_4: '',
      showType_5: '',
      showType_6: '',
      showType_7: '',
      showType_8: '',
      showType_9: '',
      showType_10: '',
      showType_11: '',
      showType_12: '',
      showType_13: '',
      showType_14: '',
      showType_15: '',
      showType_16: '',
      showType_17: '',
      showType_18: '',
      showType_19: '',
      showType_20: '',
      showType_21: '',
      showType_22: '',
      showType_23: '',
      showType_24: '',
      showType_25: '',
      showType: 'ShowType',
      formatterValid: 'Please input correct value for formatter',
      formatter: 'Formatter',
      isNullValid: 'Please input correct value for isNull',
      isNull: 'IsNull',
      validExpressionValid: 'Please input correct value for validExpression',
      validExpression: 'ValidExpression',
      validTitleValid: 'Please input correct value for validTitle',
      validTitle: 'ValidTitle',
      dictTableValid: 'Please input correct value for dictTable',
      dictTable: 'DictTable',
      dictFieldValid: 'Please input correct value for dictField',
      dictField: 'DictField',
      dictMultipleValid: 'Please input correct value for dictMultiple',
      dictMultiple: 'DictMultiple',
      dictTextValid: 'Please input correct value for dictText',
      dictText: 'DictText',
      dynaConditionValid: 'Please input correct value for dynaCondition',
      dynaCondition: 'DynaCondition',
      dictFullNameValid: 'Please input correct value for dictFullName',
      dictFullName: 'DictFullName',
      dictParentValid: 'Please input correct value for dictParent',
      dictParent: 'DictParent',
      dictParentFieldValid: 'Please input correct value for dictParentField',
      dictParentField: 'DictParentField',
      typeValid: 'Please input correct value for type',
      type_0: '',
      type_1: '',
      type_2: '',
      type_3: '',
      type_4: '',
      type_5: '',
      type_6: '',
      type_7: '',
      type_8: '',
      type_9: '',
      type_10: '',
      type_11: '',
      type_12: '',
      type_13: '',
      type_14: '',
      type_15: '',
      type_16: '',
      type_17: '',
      type_18: '',
      type_19: '',
      type_20: '',
      type_21: '',
      type_22: '',
      type_23: '',
      type_24: '',
      type_25: '',
      type: 'Type',
      length: 'Length',
      numericPrecision: 'NumericPrecision',
      numericScale: 'NumericScale',
      fkTable: 'FkTable',
      fkColumn: 'FkColumn',
      fkOnDelete_0: '同步删除子表',
      fkOnDelete_1: '设置为空',
      fkOnDelete_2: '不允许删除',
      fkOnDelete_3: '高权限不允许删除',
      fkOnDelete: 'FkOnDelete',
      fkOnUpdate_0: '同步更新子表',
      fkOnUpdate_1: '设置为空',
      fkOnUpdate_2: '不允许更新',
      fkOnUpdate_3: '高权限不允许更新',
      fkOnUpdate: 'FkOnUpdate',
      defaultQueryValue: 'DefaultQueryValue'
    }
  }
}
