export default {
  cgField: {
    title: {
      list: 'Field list',
      record: 'Field design',
      groupCgFieldTitle: 'Field properties',
      groupCgFieldDictTable: 'Dictionary',
      groupCgFieldType: 'DB properties',
      code: 'Field design'
    },
    action: {
      extDict: 'Ext dict'
    },
    field: {
      id: 'Id',
      tableIdValid: 'Please input correct value for table id',
      tableId: 'Table id',
      orderNumValid: 'Please input correct value for order num',
      orderNum: 'Order num',
      entityNameValid: 'Please input correct value for entity name',
      entityName: 'Entity name',
      titleValid: '分隔，如 名称',
      title: 'Title',
      nameValid: 'Please input correct value for name',
      name: 'Name',
      keyTypeValid: 'Please input correct value for key type',
      keyType_0: '无',
      keyType_1: '自增长主键',
      keyType_2: 'Uuid主键',
      keyType_3: '普通主键',
      keyType_4: '唯一索引',
      keyType_5: '非唯一索引',
      keyType_6: '联合唯一索引1',
      keyType_7: '联合唯一索引2',
      keyType_8: '联合唯一索引3',
      keyType: 'Key type',
      defaultValueValid: 'Please input correct value for default value',
      defaultValue: 'Default value',
      showTypeValid: 'Please input correct value for show type',
      showType: 'Show type',
      formatterValid: 'Please input correct value for formatter',
      formatter: 'Formatter',
      isNullValid: 'Please input correct value for is null',
      isNull: 'Is null',
      validExpressionValid: 'Please input correct value for valid expression',
      validExpression: 'Valid expression',
      validTitleValid: 'Please input correct value for valid title',
      validTitle: 'Valid title',
      dictTableValid: 'Please input correct value for dict table',
      dictTable: 'Dict table',
      dictFieldValid: 'Please input correct value for dict field',
      dictField: 'Dict field',
      dictMultipleValid: 'Please input correct value for dict multiple',
      dictMultiple: 'Dict multiple',
      dictTextValid: '分隔依次设置中文和英文显示值',
      dictText: 'Dict text',
      dynaConditionValid: 'Please input correct value for dyna condition',
      dynaCondition: 'Dyna condition',
      dictFullNameValid: 'Please input correct value for dict full name',
      dictFullName: 'Dict full name',
      dictParentValid: 'Please input correct value for dict parent',
      dictParent: 'Dict parent',
      dictParentFieldValid: 'Please input correct value for dict parent field',
      dictParentField: 'Dict parent field',
      typeValid: 'Please input correct value for type',
      type_0: '',
      type_1: '',
      type_2: '',
      type_3: '',
      type_4: '',
      type_5: '',
      type_6: '',
      type_7: '',
      type_8: '',
      type_9: '',
      type_10: '',
      type_11: '',
      type_12: '',
      type_13: '',
      type_14: '',
      type_15: '',
      type_16: '',
      type_17: '',
      type_18: '',
      type_19: '',
      type_20: '',
      type_21: '',
      type_22: '',
      type_23: '',
      type_24: '',
      type_25: '',
      type: 'Type',
      length: 'Length',
      numericPrecision: 'Numeric precision',
      numericScale: 'Numeric scale',
      fkTable: 'Fk table',
      fkColumn: 'Fk column',
      fkOnDelete_0: '同步删除子表',
      fkOnDelete_1: '设置为空',
      fkOnDelete_2: '不允许删除',
      fkOnDelete_3: '高权限不允许删除',
      fkOnDelete: 'Fk on delete',
      fkOnUpdate_0: '同步更新子表',
      fkOnUpdate_1: '设置为空',
      fkOnUpdate_2: '不允许更新',
      fkOnUpdate_3: '高权限不允许更新',
      fkOnUpdate: 'Fk on update',
      defaultQueryValue: 'Default query value'
    }
  }
}
