export default {
  cgList: {
    title: {
      list: 'cgList',
      join: 'cgListJoin',
      record: 'cgList',
      groupCgListTableId: 'groupCgListTableId',
      groupCgListSons: 'groupCgListSons',
      groupCgListTableHeight: 'groupCgListTableHeight',
      groupCgListImages: 'groupCgListImages',
      code: 'CgList'
    },
    route: {
      listTag: 'cgList',
      joinTag: 'cgListJoin',
      recordTag: 'cgList'
    },
    field: {
      id: 'Id',
      name: 'Name',
      pathValid: 'Please input correct value for path',
      path: 'Path',
      tableId: 'TableId',
      icon: 'Icon',
      headTitle: 'HeadTitle',
      tagTitle: 'TagTitle',
      editInline: 'EditInline',
      detailInline: 'DetailInline',
      sonsValid: 'Please input correct value for sons',
      sons: 'Sons',
      sonFieldsValid: 'Please input correct value for sonFields',
      sonFields: 'SonFields',
      sonAlign_0: '左右排列',
      sonAlign_1: '上下排列',
      sonAlign: 'SonAlign',
      generatorType: 'GeneratorType',
      titleField: 'TitleField',
      parentEntity: 'ParentEntity',
      treeShowEntity: 'TreeShowEntity',
      showSearch: 'ShowSearch',
      toolbarMode_0: '工具条',
      toolbarMode_1: '菜单',
      toolbarMode: 'ToolbarMode',
      tableHeightValid: 'Please input correct value for tableHeight',
      tableHeight: 'TableHeight',
      pagination: 'Pagination',
      orderBy: 'OrderBy',
      sortField: 'SortField',
      stripe: 'Stripe',
      border: 'Border',
      stateEntity: 'StateEntity',
      maxHeight: 'MaxHeight',
      highlightCurrentRow: 'HighlightCurrentRow',
      multiple: 'Multiple',
      showSummary: 'ShowSummary',
      spanEntities: 'SpanEntities',
      showHeader: 'ShowHeader',
      images: 'Images',
      viewProperties: 'ViewProperties',
      tableProperties: 'TableProperties',
      sonsProperties: 'SonsProperties',
      actionList: 'ActionList',
      flowDataUrl: 'FlowDataUrl',
      localExportValid: 'Please input correct value for localExport',
      localExport: 'LocalExport'
    }
  }
}
