export default {
  cgList: {
    title: {
      list: 'List',
      join: 'Select list',
      record: 'List design',
      groupCgListTableId: 'Base properties',
      groupCgListSons: 'M-S/Tree/Group',
      groupCgListTableHeight: 'Table attributes',
      groupCgListImages: 'Page design',
      code: 'List design'
    },
    field: {
      id: 'Id',
      name: 'Name',
      pathValid: 'Please input correct value for path',
      path: 'Path',
      tableId: 'Table id',
      icon: 'Icon',
      headTitleValid: '分隔，如 名称',
      headTitle: 'Head title',
      tagTitleValid: '分隔，如 名称',
      tagTitle: 'Tag title',
      editInline: 'Edit inline',
      detailInline: 'Detail inline',
      sonsValid: 'U区分.组件需要手动输入c',
      sons: 'Sons',
      sonFieldsValid: '主表关联字段Entity名,引用主表主键',
      sonFields: 'Son fields',
      sonAlign_0: '左右排列',
      sonAlign_1: '上下排列',
      sonAlign: 'Son align',
      generatorType: 'Generator type',
      titleField: 'Title field',
      parentEntity: 'Parent entity',
      treeShowEntity: 'Tree show entity',
      showSearch: 'Show search',
      toolbarMode_0: '工具条',
      toolbarMode_1: '菜单',
      toolbarMode: 'Toolbar mode',
      tableHeightValid: 'Please input correct value for table height',
      tableHeight: 'Table height',
      pagination: 'Pagination',
      orderBy: 'Order by',
      sortField: 'Sort field',
      stripe: 'Stripe',
      border: 'Border',
      stateEntity: 'State entity',
      maxHeight: 'Max height',
      highlightCurrentRow: 'Highlight current row',
      multiple: 'Multiple',
      showSummary: 'Show summary',
      spanEntities: 'Span entities',
      showHeader: 'Show header',
      images: 'Images',
      viewProperties: 'View properties',
      tableProperties: 'Table properties',
      sonsProperties: 'Sons properties',
      actionList: 'Action list',
      flowDataUrl: 'Flow data url',
      localExportValid: 'Please input correct value for local export',
      localExport: 'Local export'
    }
  }
}
