export default {
  cgList: {
    title: {
      list: '列表视图表',
      join: '列表视图选择',
      record: '列表视图',
      groupCgListTableId: '基本定义',
      groupCgListSons: '主从/树/分组',
      groupCgListTableHeight: '表格属性',
      groupCgListImages: '页面定义',
      code: '列表视图定义'
    },
    route: {
      listTag: '列表视图表',
      joinTag: '列表视图',
      recordTag: '列表视图'
    },
    field: {
      id: 'ID',
      name: '名称',
      pathValid: '只允许使用字母数字下划线并且以小写字符开始',
      path: '路径最后一级',
      tableId: '对应表单',
      icon: '图标',
      headTitle: '列表标题',
      tagTitle: 'tag标题',
      editInline: '行内编辑',
      detailInline: '行内详情',
      sonsValid: '子表为cg_list或cg_form表的名称列表,cg_form表以后缀|u区分.组件需要手动输入c|组件名称|组件路径|主见标题',
      sons: '子表',
      sonFieldsValid: '与sons对应,一个子表输入一项 : 子表关联字段Entity名|主表关联字段Entity名,引用主表主键',
      sonFields: '子表外键字段列表',
      sonAlign_0: '左右排列',
      sonAlign_1: '上下排列',
      sonAlign: '主从表排列',
      generatorType: '主表宽度',
      titleField: '显示在子表标题里的主表字段',
      parentEntity: 'tree的父级Entity',
      treeShowEntity: '树显示Entity',
      showSearch: '显示模糊查询',
      toolbarMode_0: '工具条',
      toolbarMode_1: '菜单',
      toolbarMode: '工具条显示模式',
      tableHeightValid: '设置为0表示自动匹配',
      tableHeight: '表高',
      pagination: '是否分页',
      orderBy: '默认排序',
      sortField: '拖拽排序字段',
      stripe: '斑马纹风格',
      border: '边框',
      stateEntity: '状态字段或函数',
      maxHeight: '最大高度',
      highlightCurrentRow: '单选高亮',
      multiple: '多选',
      showSummary: '统计栏',
      spanEntities: '合并字段',
      showHeader: '显示表头',
      images: '顶部轮播图像',
      viewProperties: '视图属性',
      tableProperties: '列表属性',
      sonsProperties: '子组件属性',
      actionList: '功能清单',
      flowDataUrl: '流程状态数据url',
      localExportValid: '将列表数据导出，导出数据不支持导入',
      localExport: '本地导出'
    }
  }
}
