
spring:
   http: 
      encoding:
         charset: UTF-8
         enabled: true
         force: true      
   mvc: 
      static-path-pattern: /res/**
   resources:
      static-locations: classpath:/static/
   jackson: 
      time-zone: GMT+8

server:
   port : 80
   servlet: 
      context-path : /
   tomcat:
      uri-encoding: UTF-8   
svas:
   matchTestSyncSeconds: 5  # 打开验证测试并设置同步等待时间
   matchTrace: false        # 验证跟踪
   thresh: 380              # 默认阈值
   userNoPrefix : "023"     # userNo 前缀
   userNoMminLength: 10     # userNo 最小长度

   sn : 2090-B663-7907-628A-2796-148D-6039-7195
   #sn: FFC2-EADF-E88E-80C3-7798-6ACE-0B6F-9F20
   datasource:
      host: localhost
      port: 3306
      user: root
      password: root
      schema: iotequ3
   adjust:
      autoUpdateTemplate: false   # 自动用验证数据更新字典
      templatesMustMatch: false   # 插入模板三个词典必须匹配
      multiMatchedWeight: 0       # 相同模板的多个词典多次匹配增加权重
      maxMatchedWeight: 0         # 最大匹配满足条件增加权重
      maxMatchedCondition: 100    # 最大匹配条件（差值必须大于该值)
#   url: https://www.svein.com.cn
#   client_id: svas
#   client_secret: e10adc3949ba59abbe56e057f20f883e
#   scope: api
logging: 
   file: log/svas.log
   level: 
      root: error
      org.springframework: error
      top.iotequ: error

   
