-- ----------------------------
-- Table structure for sys_user
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','SYS_USER','IOTEQU');
CREATE TABLE "IOTEQU"."SYS_USER" (
  "ID" VARCHAR2(32 BYTE) NOT NULL PRIMARY KEY,
  "ICON" CLOB NULL,
  "NAME" VARCHAR2(32 BYTE) NOT NULL UNIQUE,
  "REAL_NAME" VARCHAR2(32 BYTE) NOT NULL,
  "SEX" VARCHAR2(1 BYTE) DEFAULT '1' NULL,
  "BIRTH_DATE" DATE NULL,
  "REG_TIME" DATE NULL,
  "MOBILE_PHONE" VARCHAR2(32 BYTE) NULL UNIQUE,
  "EMAIL" VARCHAR2(50 BYTE) NULL UNIQUE,
  "WECHAT_OPENID" VARCHAR2(50 BYTE) NULL UNIQUE,
  "ORG_CODE" INTEGER NULL,
  "EMPLOYEE_NO" VARCHAR2(32 BYTE) NULL UNIQUE,
  "ORG_PRIVILEGE" INTEGER NULL,
  "ROLE_LIST" VARCHAR2(200 BYTE) NULL,
  "LOCKED" NUMBER(1) DEFAULT 0 NOT NULL,
  "STATE" NUMBER(1) DEFAULT 1 NOT NULL,
  "ID_TYPE" INTEGER DEFAULT 1 NOT NULL,
  "ID_NUMBER" VARCHAR2(45 BYTE) NOT NULL,
  "EXPIRED_TIME" DATE NULL,
  "PASSWORD_EXPIRED_TIME" DATE NULL,
  "PASSWORD" VARCHAR2(32 BYTE) DEFAULT '96e79218965eb72c92a549dd5a330112' NOT NULL,
  "PASSWORD_ERROR_TIMES" INTEGER DEFAULT 0 NOT NULL
);
CALL REMOVE_OBJECT('INDEX','INDEX_SYS_USER_ORG_CODE','IOTEQU');
CREATE INDEX "IOTEQU"."INDEX_SYS_USER_ORG_CODE" ON "IOTEQU"."SYS_USER"("ORG_CODE");

ALTER TABLE "IOTEQU"."SYS_USER" ADD CONSTRAINT  "UI_SYS_USER01" UNIQUE ("ID_TYPE","ID_NUMBER");
-- ----------------------------
-- Table structure for sys_user
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','SYS_USER','IOTEQU');
CREATE TABLE "IOTEQU"."SYS_USER" (
  "ID" VARCHAR2(32 BYTE) NOT NULL PRIMARY KEY,
  "NAME" VARCHAR2(32 BYTE) NOT NULL UNIQUE,
  "REAL_NAME" VARCHAR2(32 BYTE) NOT NULL,
  "BIRTH_DATE" DATE NULL,
  "ORG_CODE" INTEGER NULL,
  "EMPLOYEE_NO" VARCHAR2(32 BYTE) NULL UNIQUE,
  "MOBILE_PHONE" VARCHAR2(32 BYTE) NULL UNIQUE,
  "SEX" VARCHAR2(1 BYTE) DEFAULT '1' NULL,
  "LOCKED" NUMBER(1) DEFAULT 0 NOT NULL,
  "STATE" NUMBER(1) DEFAULT 1 NOT NULL,
  "ID_TYPE" INTEGER DEFAULT 1 NOT NULL,
  "ID_NUMBER" VARCHAR2(45 BYTE) NOT NULL,
  "EMAIL" VARCHAR2(50 BYTE) NULL UNIQUE,
  "REG_TIME" DATE NULL,
  "ROLE_LIST" VARCHAR2(200 BYTE) NULL,
  "ORG_PRIVILEGE" INTEGER NULL,
  "EXPIRED_TIME" DATE NULL,
  "PASSWORD_EXPIRED_TIME" DATE NULL,
  "ICON" CLOB NULL,
  "PASSWORD" VARCHAR2(32 BYTE) DEFAULT '96e79218965eb72c92a549dd5a330112' NOT NULL,
  "WECHAT_OPENID" VARCHAR2(50 BYTE) NULL UNIQUE,
  "PASSWORD_ERROR_TIMES" INTEGER DEFAULT 0 NOT NULL
);
CALL REMOVE_OBJECT('INDEX','INDEX_SYS_USER_ORG_CODE','IOTEQU');
CREATE INDEX "IOTEQU"."INDEX_SYS_USER_ORG_CODE" ON "IOTEQU"."SYS_USER"("ORG_CODE");

ALTER TABLE "IOTEQU"."SYS_USER" ADD CONSTRAINT  "UI_SYS_USER01" UNIQUE ("ID_TYPE","ID_NUMBER");
-- ----------------------------
-- Table structure for sys_task
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','SYS_TASK','IOTEQU');
CREATE TABLE "IOTEQU"."SYS_TASK" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "NAME" VARCHAR2(45 BYTE) NOT NULL,
  "DESCRIPTION" VARCHAR2(300 BYTE) NULL,
  "SCEDULE_YEARS" VARCHAR2(100 BYTE) DEFAULT '*' NOT NULL,
  "SCHEDULE_MONTHS" VARCHAR2(100 BYTE) DEFAULT '*' NOT NULL,
  "SCHEDULE_DAYS" VARCHAR2(100 BYTE) DEFAULT '*' NOT NULL,
  "SCHEDULE_WEEKS" VARCHAR2(100 BYTE) DEFAULT '*' NOT NULL,
  "SCHEDULE_HOURS" VARCHAR2(100 BYTE) DEFAULT '*' NOT NULL,
  "SCHEDULE_MINUTES" VARCHAR2(100 BYTE) DEFAULT '*' NOT NULL,
  "CLASS_NAME" VARCHAR2(100 BYTE) NOT NULL,
  "MOTHOD_NAME" VARCHAR2(500 BYTE) NOT NULL,
  "IS_STATIC" NUMBER(1) DEFAULT 1 NOT NULL,
  "PARAMES" VARCHAR2(100 BYTE) NULL,
  "IS_RUNNING" NUMBER(1) DEFAULT 1 NOT NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_SYS_TASK','IOTEQU');
CREATE SEQUENCE SEQUENCE_SYS_TASK;

-- ----------------------------
-- Table structure for sys_role
-- ----------------------------
CALL REMOVE_OBJECT('TABLE','SYS_ROLE','IOTEQU');
CREATE TABLE "IOTEQU"."SYS_ROLE" (
  "ID" INTEGER NOT NULL PRIMARY KEY,
  "CODE" VARCHAR2(8 BYTE) NOT NULL UNIQUE,
  "NAME" VARCHAR2(45 BYTE) NOT NULL UNIQUE,
  "NOTE" VARCHAR2(64 BYTE) NULL
);
CALL REMOVE_OBJECT('SEQUENCE','SEQUENCE_SYS_ROLE','IOTEQU');
CREATE SEQUENCE SEQUENCE_SYS_ROLE;

