/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_iotequ_svas_service_Svas */

#ifndef _Included_top_iotequ_svas_service_Svas
#define _Included_top_iotequ_svas_service_Svas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_getVersion
 * Signature: (Ltop/iotequ/svas/service/SvasTypes/JniStringReturn;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1getVersion
  (JNIEnv *, jclass, jobject);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_getLicence
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1getLicence
  (JNIEnv *, jclass);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_getLicenceAvailable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1getLicenceAvailable
  (JNIEnv *, jclass);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_getTrialDays
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1getTrialDays
  (JNIEnv *, jclass);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_initial
 * Signature: (Ltop/iotequ/svas/service/SvasTypes/SvasSetting;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1initial
  (JNIEnv *, jclass, jobject);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_getUserNo
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ltop/iotequ/svas/service/SvasTypes/JniStringReturn;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1getUserNo
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_getUserNoFromDict
 * Signature: (Ljava/lang/String;Ltop/iotequ/svas/service/SvasTypes/JniStringReturn;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1getUserNoFromDict
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_setUserNoForDict
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ltop/iotequ/svas/service/SvasTypes/JniStringReturn;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1setUserNoForDict
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_getUserInfo
 * Signature: (Ljava/lang/String;Ltop/iotequ/svas/service/SvasTypes/SvasUserInfo;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1getUserInfo
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_changeUserInfo
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1changeUserInfo
  (JNIEnv *, jclass, jstring, jint, jstring, jstring);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_changeUserInfoByMap
 * Signature: (Ljava/util/HashMap;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1changeUserInfoByMap
  (JNIEnv *, jclass, jobject);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_getUserAllInfo
 * Signature: (Ljava/lang/String;ILjava/util/Map;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1getUserAllInfo
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_removeUserNo
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1removeUserNo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_removeFinger
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1removeFinger
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_updateFinger
 * Signature: (Ljava/lang/String;IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1updateFinger
  (JNIEnv *, jclass, jstring, jint, jint, jstring);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_getFingerCount
 * Signature: (Ljava/lang/String;ILtop/iotequ/svas/service/SvasTypes/SvasFingerInfo;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1getFingerCount
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_getTemplates
 * Signature: (Ljava/lang/String;ILtop/iotequ/svas/service/SvasTypes/SvasTemplates;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1getTemplates
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_matchFinger
 * Signature: (Ljava/lang/String;ILtop/iotequ/svas/service/SvasTypes/SvasMatched;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1matchFinger
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_addFinger
 * Signature: (Ljava/lang/String;IILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1addFinger
  (JNIEnv *, jclass, jstring, jint, jint, jstring, jint);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_setFingers
 * Signature: (Ljava/lang/String;IILjava/lang/String;IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1setFingers
  (JNIEnv *, jclass, jstring, jint, jint, jstring, jint, jint, jstring);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_setPhoto
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1setPhoto
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     top_iotequ_svas_service_Svas
 * Method:    svein_getEnvProperties
 * Signature: (Ltop/iotequ/svas/service/SvasTypes/JniStringReturn;)I
 */
JNIEXPORT jint JNICALL Java_top_iotequ_svas_service_Svas_svein_1getEnvProperties
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
